repos:
  - repo: meta
    hooks:
    - id: check-hooks-apply
    - id: check-useless-excludes
  - repo: local
    hooks:
    - id: pre-commit-autoupdate
      name: pre-commit-autoupdate
      entry: bash -c 'pre-commit autoupdate'
      language: system
      types: [python]
      pass_filenames: false
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: check-ast
    - id: check-builtin-literals
    - id: check-docstring-first
    - id: check-merge-conflict
    - id: check-toml
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: debug-statements
    - id: mixed-line-ending
  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.1
    hooks:
    - id: absolufy-imports
      name: absolufy-imports
      files: ^INPMT/
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.252'
    hooks:
    - id: ruff
      args: ["--fix"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.0.1
    hooks:
    - id: mypy
      stages: [manual]
      additional_dependencies: [
        types-toml,
      ]
