[build-system]
requires=[
    "setuptools>=42",
    # "wheel",
    "setuptools >= 35.0.2",
    "setuptools_scm >= 2.0.0, <3"
]
build-backend="setuptools.build_meta"

[tool.setuptools_scm]
fallback_version="999"